### ISSUE TITLE
Password change and user add problem.

### ISSUE THREAD

**Issue by HAGRON** [EdoFede/Omada-EAP-Controller-Docker#1]
Hello EdoFede :)

Great JOB! Image works on NAS without official support of Docker, on Synology DS416play!

 I've got a problem with changing pass on root (docker os) and creations of new users. 

Did you try this using docker commands pushed to the docker container with password change? I was try and its not possible to change. I'm not to do bay bash in docker because root pass is unknown.

admin@HOST:/var/lib$ sudo docker exec -u 0 -it Omada-EAP-Controller passwd
Password:
Enter new UNIX password:
Retype new UNIX password:
passwd: System error
passwd: password unchanged 

P.S. Do you plan upgrade to latest version of Omada Controler?
[https://community.tp-link.com/en/business/forum/topic/162210](url)
[https://static.tp-link.com/2020/202001/20200116/Omada_Controller_v3.2.6_linux_x64.tar.gz](url)

P.S.2 Sorry for may English and I'm newbie here :)

**Comment by EdoFede** [comment]
Hi Hagron,
thank you :)

Please note that this is an "alpha" release, since I've published the repository just for testing and for integration with travis system.
I'll publish a stable release and a readme file soon.

In order to change the root password, you can issue this command from the hosts:
```bash
docker exec -u 0 -ti <container name or ID> /bin/bash -c "passwd"
```
then type 2 times the new root password.

of course, I'll update to the last version 👍

**Comment by HAGRON** [comment]
Thank you for replay :)

  I'll try to implement docker on non Intel's Synology NAS, but the app
from Synology store is not dedicated for arm processors. I'm newbie in apps
development of Synology and the one problem is that Docker compiled
directly on Synology DSM is not granted for stay if DSM will be upgraded,
probably will be flushed.

Here is link for Docker Synology DSM
<https://www.synology.com/en-us/dsm/packages/Docker> info with
compatibility listo of nas and app for x64
https://usdl.synology.com/download/Package/spk/Docker/18.09.0-0506/, if you
have any experience of this will be glad to hear you in the future :)

I'm newbie in programming to ;) but I've big experience with networking for
SMB up to Enterprise and European core networks and I have You ;). For now
I try to implement in SMB controllers of TP-Link and UniFy from Ubiquity on
cheap NASes with Arm Cores but without success :(.

Best Regards from Poland
Jacek G Kijewski (HAGRON)

P.S. If you plan visit Poland in the future, call me +48881330044 (I've got
own house near of Poznan <https://romanroams.com/en/things-to-do-poznan/>)

sob., 18 sty 2020 o 21:31 EdoFede <notifications@github.com> napisał(a):

**Comment by EdoFede** [comment]
Sorry for my late answer,

docker will run on ARM-based hardware (it works on Raspberry Pi, for example), so it would be possible to install on an ARM Syno NAS.
I've no direct experience, since I got only an intel-based Synology NAS, but I've found this discussion:
https://stackoverflow.com/questions/52520008/can-i-install-docker-on-arm8-based-synology-nas

It seems possible.
I only point out that you may have some problems with EAP controller, if your NAS has low amount of RAM, since EAP controller eat up a huge amount of memory.

I don't think I'll visit Poland soon, but in case I'll let you know. Thanks in advance! :)

**Comment by HAGRON** [comment]
Thank you for responce and link.

I'll will try install with this tutorial but Synology OS is not standard
Linux and doesn't have standard directory structure and some futures are
different i conjunction to Linux distros. When Synology OS is updated all
modification maked "by hand" are not migrateted to new version of DSM.

Regards


Sob., 15 lut 2020, 14:58 użytkownik EdoFede <notifications@github.com>
napisał:
